# Generated by Django 4.1.3 on 2022-12-21 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_alter_vagas_empresa'),
        ('vagas', '0002_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.vagas'),
        ),
    ]
